### ISSUE TITLE
Use Gulp + Sass + Bower for local development?

### ISSUE THREAD

**Issue by mattrothenberg** [DevProgress/devprogress.github.io#10]
Hi all,

I've started a branch (https://github.com/DevProgress/devprogress.github.io/tree/gulp-sass-spike) that introduces Gulp + Sass + Bower to improve the local dev experience. 
# Getting Started

Be sure you have Gulp installed.

```
npm install --global gulp-cli
```

and Bower

```
npm install --global bower
```

Check out the branch and install the required Node modules and Bower components

```
npm install && bower install
```

Spin up a server for local development

```
python -m SimpleHTTPServer
```

Run the default Gulp task, which watches changes to `main.scss` and spits out a `main.css` in the `assets/css` directory. You'll need to refresh your browser to see changes, though this could easily be fixed by introducing some kind of `livereload` mechanism. 

```
gulp
```
# Wishlist
- [ ] Livereloading
- [ ] Build script (Minification + Uglification of code)

As always, please holler if there are questions!

**Comment by decause** [comment]
Awesome.
Question: I realize that minification helps with load time, but it's the uglification that has always puzzled me. Is there a reason we want to obfuscate? I'm genuinely curious.

**Comment by kahneraja** [comment]
i like this a lot! i guess for larger projects this would be helpful - but it's a great idea to set it up so when this things explodes we are ready.

@mattrothenberg, if you are working on this one please "assign" it to yourself so others don't duplicate the effort.

**Comment by samuelcole** [comment]
@decause uglification/minification are usually synonyms, i've worked on 'proprietary' front-ends at start ups, and i've never experienced anyone wanting to uglify beyond what a minnifier would do.

**Comment by decause** [comment]
@samuelcole @kahneraja 

looks like this is done, yeah?

**Comment by samuelcole** [comment]
yup!
