### ISSUE TITLE
Devprogress.us Projects Gallery

### ISSUE THREAD

**Issue by decause** [DevProgress/devprogress.github.io#21]
http://devprogress.us/projects

We've come a long way in such a short time :) We've reached the point where we could use some kind of grid or gallery of shipped projects and tools?

**Comment by decause** [comment]
- [x] csv-simple-search
- [x] Latinos for Hillary
- [x] Labor for Hillary
- [x] Women for Hillary
- [x] gcalbridge demo video (maybe fork an above microsite for this one ;) )
- [x] HillaryBNB
- [x] hrc-events
- [x] landing page
- [ ] others I'm missing?

**Comment by mattrothenberg** [comment]
I'll take a stab at this tomorrow, @decause

**Comment by mattrothenberg** [comment]
First pass is up at https://github.com/DevProgress/devprogress.github.io/tree/projects-page-grid.

Looking forward to discussing over Show & Tell tonight 💯

**Comment by jillh510** [comment]
The gallery is looking good! Can this issue be closed?

**Comment by decause** [comment]
Yep! Thanks @jillh510
