### ISSUE TITLE
Blue Section is Abnormally Large on Large Screens

### ISSUE THREAD

**Issue by mattrothenberg** [DevProgress/devprogress.github.io#6]
Need to adjust column widths on larger viewports.

![pasted_image_at_2016_08_06_04_47_pm](https://cloud.githubusercontent.com/assets/5148596/17459793/c0355f14-5c16-11e6-990b-795fc6f515da.png)

**Comment by kahneraja** [comment]
what should max-width be @mattrothenberg?

**Comment by mattrothenberg** [comment]
Resolved by https://github.com/DevProgress/devprogress.github.io/pull/9
